// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_SESSION: KVNamespace;
	KV_CACHE: KVNamespace;
	WANDBOX_URL_PREFIX: "https://api-develop.wandbox.org";
	WANDBOX_GITHUB_CLIENT_ID: "d097a8f338db3c15fe08";
	WANDBOX_GITHUB_CLIENT_SECRET: string;
	WANDBOX_KV_COOKIE_SECRET: string;
}
