name: Deploy develop.wandbox.org

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Register SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
    - name: Add SSH config
      env:
        SSH_HOST: ${{ secrets.SSH_HOST_UBUNTU_24_04 }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        set -ex
        echo "Host wandbox-ubuntu-24.04" >> $HOME/.ssh/config
        echo "    HostName $SSH_HOST" >> $HOME/.ssh/config
        echo "    User $SSH_USER" >> $HOME/.ssh/config
        echo "    ServerAliveInterval 60" >> $HOME/.ssh/config
        echo "    TCPKeepAlive yes" >> $HOME/.ssh/config
        ssh-keyscan -H $SSH_HOST >> $HOME/.ssh/known_hosts
    - name: Deploy feline to develop.wandbox.org
      run: |
        python3 run.py package feline --env develop
        python3 run.py deploy wandbox-ubuntu-24.04 feline --env develop
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '22'
    - name: Cache node modules
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      env:
        cache-name: cache-node-modules-v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('canine/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # - name: Build Workers
    #   working-directory: canine
    #   run: |
    #     set -ex
    #     npm install
    #     npm run build
    # - name: Publish canine
    #   working-directory: canine
    #   env:
    #     CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    #   run: |
    #     set -ex
    #     npm install -g @cloudflare/wrangler
    #     npm run deploy:develop
